// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using Northwind.MSSQL.Models;

namespace Northwind.MSSQL.Data
{
    public partial class NorthwindContext
    {

        [DbFunction("GetTotalProductValue", "dbo")]
        public static decimal? GetTotalProductValue(int? productId)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
